# Generated by Django 3.2.5 on 2021-07-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='text_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=500)),
                ('m_date', models.CharField(max_length=20)),
                ('c_date', models.CharField(max_length=20)),
            ],
        ),
    ]
