# Generated by Django 3.2.5 on 2021-07-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSV_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hash', models.CharField(max_length=50)),
                ('Emp_ID', models.CharField(max_length=50)),
                ('Name_Prefix', models.CharField(max_length=50)),
                ('First_Name', models.CharField(max_length=50)),
                ('Middle_Initial', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Father_Name', models.CharField(max_length=50)),
                ('Mother_Name', models.CharField(max_length=50)),
                ('Full_Name', models.CharField(max_length=50)),
            ],
        ),
    ]
